// <auto-generated>
// 이 파일은 자동 생성되므로 직접 수정하지 마세요!
// InputSystem_Actions.inputactions 파일이 변경되면 자동으로 재생성됩니다.
// 수동 생성: Tools > Input > Generate Input Manager Code
// </auto-generated>

using System;
using UnityEngine;

/// <summary>
/// 중앙 입력 관리자 (자동 생성 부분)
/// </summary>
public partial class InputManager
{
    #region Player Action Events

    /// <summary>
    /// Move 액션 이벤트 (Vector2)
    /// </summary>
    public event Action<Vector2> OnMove;

    /// <summary>
    /// Look 액션 이벤트 (Vector2)
    /// </summary>
    public event Action<Vector2> OnLook;

    /// <summary>
    /// Attack 액션 Started 이벤트
    /// </summary>
    public event Action OnAttackStarted;

    /// <summary>
    /// Attack 액션 Performed 이벤트
    /// </summary>
    public event Action OnAttackPerformed;

    /// <summary>
    /// Attack 액션 Canceled 이벤트
    /// </summary>
    public event Action OnAttackCanceled;

    /// <summary>
    /// Interact 액션 Started 이벤트
    /// </summary>
    public event Action OnInteractStarted;

    /// <summary>
    /// Interact 액션 Performed 이벤트
    /// </summary>
    public event Action OnInteractPerformed;

    /// <summary>
    /// Interact 액션 Canceled 이벤트
    /// </summary>
    public event Action OnInteractCanceled;

    /// <summary>
    /// Crouch 액션 Started 이벤트
    /// </summary>
    public event Action OnCrouchStarted;

    /// <summary>
    /// Crouch 액션 Performed 이벤트
    /// </summary>
    public event Action OnCrouchPerformed;

    /// <summary>
    /// Crouch 액션 Canceled 이벤트
    /// </summary>
    public event Action OnCrouchCanceled;

    /// <summary>
    /// Jump 액션 Started 이벤트
    /// </summary>
    public event Action OnJumpStarted;

    /// <summary>
    /// Jump 액션 Performed 이벤트
    /// </summary>
    public event Action OnJumpPerformed;

    /// <summary>
    /// Jump 액션 Canceled 이벤트
    /// </summary>
    public event Action OnJumpCanceled;

    /// <summary>
    /// Previous 액션 Started 이벤트
    /// </summary>
    public event Action OnPreviousStarted;

    /// <summary>
    /// Previous 액션 Performed 이벤트
    /// </summary>
    public event Action OnPreviousPerformed;

    /// <summary>
    /// Previous 액션 Canceled 이벤트
    /// </summary>
    public event Action OnPreviousCanceled;

    /// <summary>
    /// Next 액션 Started 이벤트
    /// </summary>
    public event Action OnNextStarted;

    /// <summary>
    /// Next 액션 Performed 이벤트
    /// </summary>
    public event Action OnNextPerformed;

    /// <summary>
    /// Next 액션 Canceled 이벤트
    /// </summary>
    public event Action OnNextCanceled;

    /// <summary>
    /// Sprint 액션 Started 이벤트
    /// </summary>
    public event Action OnSprintStarted;

    /// <summary>
    /// Sprint 액션 Performed 이벤트
    /// </summary>
    public event Action OnSprintPerformed;

    /// <summary>
    /// Sprint 액션 Canceled 이벤트
    /// </summary>
    public event Action OnSprintCanceled;

    #endregion

    #region UI Action Events

    /// <summary>
    /// Navigate 액션 이벤트 (Vector2)
    /// </summary>
    public event Action<Vector2> OnNavigate;

    /// <summary>
    /// Submit 액션 Started 이벤트
    /// </summary>
    public event Action OnSubmitStarted;

    /// <summary>
    /// Submit 액션 Performed 이벤트
    /// </summary>
    public event Action OnSubmitPerformed;

    /// <summary>
    /// Submit 액션 Canceled 이벤트
    /// </summary>
    public event Action OnSubmitCanceled;

    /// <summary>
    /// Cancel 액션 Started 이벤트
    /// </summary>
    public event Action OnCancelStarted;

    /// <summary>
    /// Cancel 액션 Performed 이벤트
    /// </summary>
    public event Action OnCancelPerformed;

    /// <summary>
    /// Cancel 액션 Canceled 이벤트
    /// </summary>
    public event Action OnCancelCanceled;

    /// <summary>
    /// Point 액션 이벤트 (Vector2)
    /// </summary>
    public event Action<Vector2> OnPoint;

    /// <summary>
    /// Click 액션 Started 이벤트
    /// </summary>
    public event Action OnClickStarted;

    /// <summary>
    /// Click 액션 Performed 이벤트
    /// </summary>
    public event Action OnClickPerformed;

    /// <summary>
    /// Click 액션 Canceled 이벤트
    /// </summary>
    public event Action OnClickCanceled;

    /// <summary>
    /// RightClick 액션 Started 이벤트
    /// </summary>
    public event Action OnRightClickStarted;

    /// <summary>
    /// RightClick 액션 Performed 이벤트
    /// </summary>
    public event Action OnRightClickPerformed;

    /// <summary>
    /// RightClick 액션 Canceled 이벤트
    /// </summary>
    public event Action OnRightClickCanceled;

    /// <summary>
    /// MiddleClick 액션 Started 이벤트
    /// </summary>
    public event Action OnMiddleClickStarted;

    /// <summary>
    /// MiddleClick 액션 Performed 이벤트
    /// </summary>
    public event Action OnMiddleClickPerformed;

    /// <summary>
    /// MiddleClick 액션 Canceled 이벤트
    /// </summary>
    public event Action OnMiddleClickCanceled;

    /// <summary>
    /// ScrollWheel 액션 이벤트 (Vector2)
    /// </summary>
    public event Action<Vector2> OnScrollWheel;

    /// <summary>
    /// TrackedDevicePosition 액션 이벤트 (Vector3)
    /// </summary>
    public event Action<Vector3> OnTrackedDevicePosition;

    /// <summary>
    /// TrackedDeviceOrientation 액션 이벤트 (Quaternion)
    /// </summary>
    public event Action<Quaternion> OnTrackedDeviceOrientation;

    #endregion

    #region Player Binding

    /// <summary>
    /// Player 액션 바인딩
    /// </summary>
    private void BindPlayerActions()
    {
        // Move
        inputActions.Player.Move.performed += ctx => OnMove?.Invoke(ctx.ReadValue<Vector2>());
        inputActions.Player.Move.canceled += ctx => OnMove?.Invoke(Vector2.zero);

        // Look
        inputActions.Player.Look.performed += ctx => OnLook?.Invoke(ctx.ReadValue<Vector2>());
        inputActions.Player.Look.canceled += ctx => OnLook?.Invoke(Vector2.zero);

        // Attack
        inputActions.Player.Attack.started += ctx => OnAttackStarted?.Invoke();
        inputActions.Player.Attack.performed += ctx => OnAttackPerformed?.Invoke();
        inputActions.Player.Attack.canceled += ctx => OnAttackCanceled?.Invoke();

        // Interact
        inputActions.Player.Interact.started += ctx => OnInteractStarted?.Invoke();
        inputActions.Player.Interact.performed += ctx => OnInteractPerformed?.Invoke();
        inputActions.Player.Interact.canceled += ctx => OnInteractCanceled?.Invoke();

        // Crouch
        inputActions.Player.Crouch.started += ctx => OnCrouchStarted?.Invoke();
        inputActions.Player.Crouch.performed += ctx => OnCrouchPerformed?.Invoke();
        inputActions.Player.Crouch.canceled += ctx => OnCrouchCanceled?.Invoke();

        // Jump
        inputActions.Player.Jump.started += ctx => OnJumpStarted?.Invoke();
        inputActions.Player.Jump.performed += ctx => OnJumpPerformed?.Invoke();
        inputActions.Player.Jump.canceled += ctx => OnJumpCanceled?.Invoke();

        // Previous
        inputActions.Player.Previous.started += ctx => OnPreviousStarted?.Invoke();
        inputActions.Player.Previous.performed += ctx => OnPreviousPerformed?.Invoke();
        inputActions.Player.Previous.canceled += ctx => OnPreviousCanceled?.Invoke();

        // Next
        inputActions.Player.Next.started += ctx => OnNextStarted?.Invoke();
        inputActions.Player.Next.performed += ctx => OnNextPerformed?.Invoke();
        inputActions.Player.Next.canceled += ctx => OnNextCanceled?.Invoke();

        // Sprint
        inputActions.Player.Sprint.started += ctx => OnSprintStarted?.Invoke();
        inputActions.Player.Sprint.performed += ctx => OnSprintPerformed?.Invoke();
        inputActions.Player.Sprint.canceled += ctx => OnSprintCanceled?.Invoke();

    }

    #endregion

    #region UI Binding

    /// <summary>
    /// UI 액션 바인딩
    /// </summary>
    private void BindUIActions()
    {
        // Navigate
        inputActions.UI.Navigate.performed += ctx => OnNavigate?.Invoke(ctx.ReadValue<Vector2>());
        inputActions.UI.Navigate.canceled += ctx => OnNavigate?.Invoke(Vector2.zero);

        // Submit
        inputActions.UI.Submit.started += ctx => OnSubmitStarted?.Invoke();
        inputActions.UI.Submit.performed += ctx => OnSubmitPerformed?.Invoke();
        inputActions.UI.Submit.canceled += ctx => OnSubmitCanceled?.Invoke();

        // Cancel
        inputActions.UI.Cancel.started += ctx => OnCancelStarted?.Invoke();
        inputActions.UI.Cancel.performed += ctx => OnCancelPerformed?.Invoke();
        inputActions.UI.Cancel.canceled += ctx => OnCancelCanceled?.Invoke();

        // Point
        inputActions.UI.Point.performed += ctx => OnPoint?.Invoke(ctx.ReadValue<Vector2>());
        inputActions.UI.Point.canceled += ctx => OnPoint?.Invoke(Vector2.zero);

        // Click
        inputActions.UI.Click.started += ctx => OnClickStarted?.Invoke();
        inputActions.UI.Click.performed += ctx => OnClickPerformed?.Invoke();
        inputActions.UI.Click.canceled += ctx => OnClickCanceled?.Invoke();

        // RightClick
        inputActions.UI.RightClick.started += ctx => OnRightClickStarted?.Invoke();
        inputActions.UI.RightClick.performed += ctx => OnRightClickPerformed?.Invoke();
        inputActions.UI.RightClick.canceled += ctx => OnRightClickCanceled?.Invoke();

        // MiddleClick
        inputActions.UI.MiddleClick.started += ctx => OnMiddleClickStarted?.Invoke();
        inputActions.UI.MiddleClick.performed += ctx => OnMiddleClickPerformed?.Invoke();
        inputActions.UI.MiddleClick.canceled += ctx => OnMiddleClickCanceled?.Invoke();

        // ScrollWheel
        inputActions.UI.ScrollWheel.performed += ctx => OnScrollWheel?.Invoke(ctx.ReadValue<Vector2>());
        inputActions.UI.ScrollWheel.canceled += ctx => OnScrollWheel?.Invoke(Vector2.zero);

        // TrackedDevicePosition
        inputActions.UI.TrackedDevicePosition.performed += ctx => OnTrackedDevicePosition?.Invoke(ctx.ReadValue<Vector3>());
        inputActions.UI.TrackedDevicePosition.canceled += ctx => OnTrackedDevicePosition?.Invoke(Vector3.zero);

        // TrackedDeviceOrientation
        inputActions.UI.TrackedDeviceOrientation.performed += ctx => OnTrackedDeviceOrientation?.Invoke(ctx.ReadValue<Quaternion>());
        inputActions.UI.TrackedDeviceOrientation.canceled += ctx => OnTrackedDeviceOrientation?.Invoke(Quaternion.identity);

    }

    #endregion

    /// <summary>
    /// 모든 액션 바인딩
    /// </summary>
    private void BindAllActions()
    {
        BindPlayerActions();
        BindUIActions();
    }

    #region Player Get Methods

    /// <summary>
    /// Move 입력 값 조회
    /// </summary>
    public Vector2 GetMoveInput()
    {
        return inputActions.Player.Move.ReadValue<Vector2>();
    }

    /// <summary>
    /// Look 입력 값 조회
    /// </summary>
    public Vector2 GetLookInput()
    {
        return inputActions.Player.Look.ReadValue<Vector2>();
    }

    /// <summary>
    /// Attack 버튼 눌림 상태 조회
    /// </summary>
    public bool IsAttackPressed()
    {
        return inputActions.Player.Attack.IsPressed();
    }

    /// <summary>
    /// Interact 버튼 눌림 상태 조회
    /// </summary>
    public bool IsInteractPressed()
    {
        return inputActions.Player.Interact.IsPressed();
    }

    /// <summary>
    /// Crouch 버튼 눌림 상태 조회
    /// </summary>
    public bool IsCrouchPressed()
    {
        return inputActions.Player.Crouch.IsPressed();
    }

    /// <summary>
    /// Jump 버튼 눌림 상태 조회
    /// </summary>
    public bool IsJumpPressed()
    {
        return inputActions.Player.Jump.IsPressed();
    }

    /// <summary>
    /// Previous 버튼 눌림 상태 조회
    /// </summary>
    public bool IsPreviousPressed()
    {
        return inputActions.Player.Previous.IsPressed();
    }

    /// <summary>
    /// Next 버튼 눌림 상태 조회
    /// </summary>
    public bool IsNextPressed()
    {
        return inputActions.Player.Next.IsPressed();
    }

    /// <summary>
    /// Sprint 버튼 눌림 상태 조회
    /// </summary>
    public bool IsSprintPressed()
    {
        return inputActions.Player.Sprint.IsPressed();
    }

    #endregion

    #region UI Get Methods

    /// <summary>
    /// Navigate 입력 값 조회
    /// </summary>
    public Vector2 GetNavigateInput()
    {
        return inputActions.UI.Navigate.ReadValue<Vector2>();
    }

    /// <summary>
    /// Submit 버튼 눌림 상태 조회
    /// </summary>
    public bool IsSubmitPressed()
    {
        return inputActions.UI.Submit.IsPressed();
    }

    /// <summary>
    /// Cancel 버튼 눌림 상태 조회
    /// </summary>
    public bool IsCancelPressed()
    {
        return inputActions.UI.Cancel.IsPressed();
    }

    /// <summary>
    /// Point 입력 값 조회
    /// </summary>
    public Vector2 GetPointInput()
    {
        return inputActions.UI.Point.ReadValue<Vector2>();
    }

    /// <summary>
    /// Click 버튼 눌림 상태 조회
    /// </summary>
    public bool IsClickPressed()
    {
        return inputActions.UI.Click.IsPressed();
    }

    /// <summary>
    /// RightClick 버튼 눌림 상태 조회
    /// </summary>
    public bool IsRightClickPressed()
    {
        return inputActions.UI.RightClick.IsPressed();
    }

    /// <summary>
    /// MiddleClick 버튼 눌림 상태 조회
    /// </summary>
    public bool IsMiddleClickPressed()
    {
        return inputActions.UI.MiddleClick.IsPressed();
    }

    /// <summary>
    /// ScrollWheel 입력 값 조회
    /// </summary>
    public Vector2 GetScrollWheelInput()
    {
        return inputActions.UI.ScrollWheel.ReadValue<Vector2>();
    }

    /// <summary>
    /// TrackedDevicePosition 입력 값 조회
    /// </summary>
    public Vector3 GetTrackedDevicePositionInput()
    {
        return inputActions.UI.TrackedDevicePosition.ReadValue<Vector3>();
    }

    /// <summary>
    /// TrackedDeviceOrientation 입력 값 조회
    /// </summary>
    public Quaternion GetTrackedDeviceOrientationInput()
    {
        return inputActions.UI.TrackedDeviceOrientation.ReadValue<Quaternion>();
    }

    #endregion

}
