#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using System.Collections.Generic;

/// <summary>
/// InputSystem_Actions.inputactions 파일을 파싱하여
/// InputManager.Generated.cs 파일을 자동 생성하는 에디터 툴
/// </summary>
public class InputActionCodeGenerator
{
    private const string INPUT_ACTIONS_PATH = "Assets/Input/InputSystem_Actions.inputactions";
    private const string OUTPUT_PATH = "Assets/Scripts/Core/Input/InputManager.Generated.cs";

    /// <summary>
    /// 메뉴에서 수동으로 코드 생성
    /// </summary>
    [MenuItem("Tools/Input/Generate Input Manager Code")]
    public static void GenerateCodeManually()
    {
        GenerateCode();
    }

    /// <summary>
    /// 코드 생성 (AssetPostprocessor에서도 호출됨)
    /// </summary>
    public static void GenerateCode()
    {
        try
        {
            // .inputactions 파일 존재 확인
            if (!File.Exists(INPUT_ACTIONS_PATH))
            {
                Debug.LogError($"[InputManager] InputActions 파일을 찾을 수 없습니다: {INPUT_ACTIONS_PATH}");
                return;
            }

            // .inputactions 파일 읽기
            string json = File.ReadAllText(INPUT_ACTIONS_PATH);

            // JSON 파싱
            var inputData = ParseInputActionsJson(json);

            if (inputData == null || inputData.maps == null || inputData.maps.Count == 0)
            {
                Debug.LogError("[InputManager] InputActions 파일 파싱 실패");
                return;
            }

            // 코드 생성
            string generatedCode = GenerateInputManagerCode(inputData);

            // 출력 디렉토리 생성 (없으면)
            string directory = Path.GetDirectoryName(OUTPUT_PATH);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            // 파일 저장
            File.WriteAllText(OUTPUT_PATH, generatedCode, Encoding.UTF8);

            // Unity에 알림
            AssetDatabase.Refresh();

            Debug.Log($"[InputManager] 코드 자동 생성 완료: {OUTPUT_PATH}");
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[InputManager] 코드 생성 중 오류 발생: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// JSON 파싱
    /// </summary>
    private static InputActionsData ParseInputActionsJson(string json)
    {
        try
        {
            var data = JsonUtility.FromJson<InputActionsData>(json);
            return data;
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[InputManager] JSON 파싱 오류: {e.Message}");
            return null;
        }
    }

    /// <summary>
    /// InputManager.Generated.cs 코드 생성
    /// </summary>
    private static string GenerateInputManagerCode(InputActionsData data)
    {
        StringBuilder sb = new StringBuilder();

        // 헤더
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 이 파일은 자동 생성되므로 직접 수정하지 마세요!");
        sb.AppendLine("// InputSystem_Actions.inputactions 파일이 변경되면 자동으로 재생성됩니다.");
        sb.AppendLine("// 수동 생성: Tools > Input > Generate Input Manager Code");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();

        // partial class 시작
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 중앙 입력 관리자 (자동 생성 부분)");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class InputManager");
        sb.AppendLine("{");

        // 각 Action Map별로 이벤트 생성
        foreach (var map in data.maps)
        {
            GenerateEvents(sb, map);
            sb.AppendLine();
        }

        // 각 Action Map별로 바인딩 메서드 생성
        foreach (var map in data.maps)
        {
            GenerateBindingMethod(sb, map);
            sb.AppendLine();
        }

        // BindAllActions 메서드
        GenerateBindAllMethod(sb, data.maps);
        sb.AppendLine();

        // 각 Action Map별로 Get 메서드 생성
        foreach (var map in data.maps)
        {
            GenerateGetMethods(sb, map);
            sb.AppendLine();
        }

        // partial class 종료
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 이벤트 선언 생성
    /// </summary>
    private static void GenerateEvents(StringBuilder sb, ActionMap map)
    {
        sb.AppendLine($"    #region {map.name} Action Events");
        sb.AppendLine();

        foreach (var action in map.actions)
        {
            string actionType = action.expectedControlType;

            if (actionType == "Vector2")
            {
                // Vector2 타입 이벤트
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 이벤트 (Vector2)");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action<Vector2> On{action.name};");
                sb.AppendLine();
            }
            else if (actionType == "Button")
            {
                // Button 타입 이벤트 (Started, Performed, Canceled)
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 Started 이벤트");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action On{action.name}Started;");
                sb.AppendLine();

                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 Performed 이벤트");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action On{action.name}Performed;");
                sb.AppendLine();

                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 Canceled 이벤트");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action On{action.name}Canceled;");
                sb.AppendLine();
            }
            else if (actionType == "Quaternion")
            {
                // Quaternion 타입 이벤트
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 이벤트 (Quaternion)");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action<Quaternion> On{action.name};");
                sb.AppendLine();
            }
            else if (actionType == "Vector3")
            {
                // Vector3 타입 이벤트
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 액션 이벤트 (Vector3)");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public event Action<Vector3> On{action.name};");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"    #endregion");
    }

    /// <summary>
    /// 바인딩 메서드 생성
    /// </summary>
    private static void GenerateBindingMethod(StringBuilder sb, ActionMap map)
    {
        sb.AppendLine($"    #region {map.name} Binding");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {map.name} 액션 바인딩");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    private void Bind{map.name}Actions()");
        sb.AppendLine($"    {{");

        foreach (var action in map.actions)
        {
            string actionType = action.expectedControlType;

            if (actionType == "Vector2")
            {
                sb.AppendLine($"        // {action.name}");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.performed += ctx => On{action.name}?.Invoke(ctx.ReadValue<Vector2>());");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.canceled += ctx => On{action.name}?.Invoke(Vector2.zero);");
                sb.AppendLine();
            }
            else if (actionType == "Button")
            {
                sb.AppendLine($"        // {action.name}");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.started += ctx => On{action.name}Started?.Invoke();");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.performed += ctx => On{action.name}Performed?.Invoke();");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.canceled += ctx => On{action.name}Canceled?.Invoke();");
                sb.AppendLine();
            }
            else if (actionType == "Quaternion")
            {
                sb.AppendLine($"        // {action.name}");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.performed += ctx => On{action.name}?.Invoke(ctx.ReadValue<Quaternion>());");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.canceled += ctx => On{action.name}?.Invoke(Quaternion.identity);");
                sb.AppendLine();
            }
            else if (actionType == "Vector3")
            {
                sb.AppendLine($"        // {action.name}");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.performed += ctx => On{action.name}?.Invoke(ctx.ReadValue<Vector3>());");
                sb.AppendLine($"        inputActions.{map.name}.{action.name}.canceled += ctx => On{action.name}?.Invoke(Vector3.zero);");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    #endregion");
    }

    /// <summary>
    /// Get 메서드 생성
    /// </summary>
    private static void GenerateGetMethods(StringBuilder sb, ActionMap map)
    {
        sb.AppendLine($"    #region {map.name} Get Methods");
        sb.AppendLine();

        foreach (var action in map.actions)
        {
            string actionType = action.expectedControlType;

            if (actionType == "Vector2")
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 입력 값 조회");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public Vector2 Get{action.name}Input()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        return inputActions.{map.name}.{action.name}.ReadValue<Vector2>();");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
            else if (actionType == "Button")
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 버튼 눌림 상태 조회");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public bool Is{action.name}Pressed()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        return inputActions.{map.name}.{action.name}.IsPressed();");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
            else if (actionType == "Quaternion")
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 입력 값 조회");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public Quaternion Get{action.name}Input()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        return inputActions.{map.name}.{action.name}.ReadValue<Quaternion>();");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
            else if (actionType == "Vector3")
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {action.name} 입력 값 조회");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public Vector3 Get{action.name}Input()");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        return inputActions.{map.name}.{action.name}.ReadValue<Vector3>();");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"    #endregion");
    }

    /// <summary>
    /// BindAllActions 메서드 생성
    /// </summary>
    private static void GenerateBindAllMethod(StringBuilder sb, List<ActionMap> maps)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 모든 액션 바인딩");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    private void BindAllActions()");
        sb.AppendLine($"    {{");

        foreach (var map in maps)
        {
            sb.AppendLine($"        Bind{map.name}Actions();");
        }

        sb.AppendLine($"    }}");
    }

    #region JSON 파싱용 데이터 클래스

    [System.Serializable]
    private class InputActionsData
    {
        public List<ActionMap> maps;
    }

    [System.Serializable]
    private class ActionMap
    {
        public string name;
        public List<ActionData> actions;
    }

    [System.Serializable]
    private class ActionData
    {
        public string name;
        public string type;
        public string expectedControlType;
    }

    #endregion
}
#endif
